# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b370b8fab5301f332a95467f26ae31b63551f0c2a02c17aef8647c9adcf54edeb02263fdfbcf7298a9f6785583bcdb5c7ce8405055c86eb22e887c8212be3cb

test:
  secret_key_base: bf0fed017778a6fefb78c77a5732cef5e86e27f534806a327180648367c6df8b5c059eaeff7f7fa1680196dc1282783b179b2beeecfedc04f49cdeda17332d6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
